#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites. Assumes that the execution environment
has `requirements-dev.txt` installed.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint
        flake8 stacframes tests

        # Code formatting
        black --check stacframes tests

        # Run tests
        python -m unittest discover tests
    fi
fi
